"""
Django settings for djangoproject project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
from datetime import datetime
import os

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '<SOMETHING_SECRET_TO_REDEFINE_HERE>'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
JS_DEBUG = False

ALLOWED_HOSTS = ['.localhost']

# Add private IP from AWS
# cfr. https://hashedin.com/blog/5-gotchas-with-elastic-beanstalk-and-django/
def is_ec2_linux():
    """Detect if we are running on an EC2 Linux Instance

       See http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html
    """
    if os.path.isfile("/sys/hypervisor/uuid"):
        with open("/sys/hypervisor/uuid") as f:
            uuid = f.read()
            return uuid.startswith("ec2")
    return False

def get_linux_ec2_private_ip():
    """Get the private IP Address of the machine if running
    on an EC2 linux server
    """
    from urllib import request
    if not is_ec2_linux():
        return None
    try:
        response = request.urlopen('http://169.254.169.254/latest/meta-data/local-ipv4')
        return response.read()
    except:
        return None
    finally:
        if response:
            response.close()
# ElasticBeanstalk healthcheck sends requests with host header = internal ip
# So we detect if we are in elastic beanstalk, and add the instances private ip address
private_ip = get_linux_ec2_private_ip()
if private_ip:
    ALLOWED_HOSTS.append(private_ip)

# Application definition

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

INSTALLED_APPS = [
    'modeltranslation',  # MUST be before Admin, see https://github.com/deschler/django-modeltranslation/issues/408

    # From Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.gis',
    'django.contrib.humanize',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.staticfiles',

    # From others
    'crispy_forms',
    'markdownx',
    'imagekit',
    'import_export',
    'constance',
    'constance.backends.database',

    # Local helpers
    'page_fragments',

    'vespawatch',

    'django_cleanup.apps.CleanupConfig',  # Must be placed last, according to doc
]


CONSTANCE_CONFIG = {
    'LAST_PULL_COMPLETED_AT': (datetime(2019, 7, 15, 0, 0, 0),
                              'The last time the iNaturalist sync pull operation successfully completed'),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]

ROOT_URLCONF = 'djangoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_settings_export.settings_export'
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Brussels'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('nl', _('Dutch')),
    ('en', _('English')),
    ('fr', _('French'))
]

PAGE_FRAGMENTS_FALLBACK_LANGUAGE = 'nl'

LOCALE_PATHS = (os.path.join(BASE_DIR, os.pardir, 'locale'), os.path.join(BASE_DIR, 'locale'), )

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

MEDIA_URL = '/img/'
STATIC_URL = '/static/'


# ---------- Custom settings ----------

# Map

MAP_CIRCLE_FILL_OPACITY = 0.5
MAP_CIRCLE_STROKE_OPACITY = 0.8
MAP_CIRCLE_STROKE_WIDTH = 1
MAP_CIRCLE_NEST_RADIUS = 12
MAP_CIRCLE_INDIVIDUAL_RADIUS = 5
MAP_CIRCLE_INDIVIDUAL_COLOR = '#fd9126'
MAP_CIRCLE_NEST_COLOR = {  # This depend of the management action
    'finished': '#9ccb19',
    'unfinished': '#ee4000',
    'DEFAULT': '#73984a'
}
MAP_CIRCLE_UNKNOWN_COLOR = '#000' # if the subject is not 'Individual' or 'Nest'
MAP_INITIAL_POSITION = [50.85, 4.35]
MAP_INITIAL_ZOOM = 8

MAP_TILELAYER_BASE_URL = 'https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}{r}.png'
MAP_TILELAYER_OPTIONS = {
    'attribution': '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="http://carto.com/attributions">CARTO</a>',
    'subdomains': 'abcd',
    'maxZoom': 20
}

# iNaturalist

INAT_USER_USERNAME = 'vespawatch'
INAT_USER_PASSWORD = ''
INAT_APP_ID = 'd1d0f541791be42e234ce82a5bb8332ab816ff7ab35c6e27b12c0455939a5ea8'
INAT_APP_SECRET = ''
INATURALIST_PUSH = False

# Notification emails

EMAIL_TO_REPORTER_SENDER = 'vespawatch@inbo.be'
EMAIL_TO_REPORTER_SUBJECT = 'Bedankt voor je melding op Vespa-Watch / Merci pour votre observation sur Vespa-Watch'
EMAIL_TO_REPORTER_BODY = """
<html>
<body>
    <small><p>(version française ci-dessous)</p></small>
    <p>Beste{observer_name},</p>

    <p>
    Bedankt voor je melding op <a href="https://vespawatch.be">Vespa-Watch</a>. Dankzij jou houden 
    we de vinger aan de pols van de Aziatische hoornaarinvasie in Vlaanderen.</p>
    
    <p>
    Je observatie is nu ook beschikbaar op 
    <a href="https://www.inaturalist.org/observations/{inat_id}">iNaturalist</a>, waar deze door 
    vrijwilligers kan worden geverifieerd. Observaties met onbruikbare of niet zelf genomen foto's 
    zullen worden verwijderd. Hou 
    <a href="https://www.inaturalist.org/observations/{inat_id}">deze pagina</a> in de gaten om te 
    weten welke soort je hebt gezien. Wil je deelnemen aan de identificatie en/of observaties onder 
    je eigen naam doorsturen? Maak dan een <a href="https://www.inaturalist.org/signup">iNaturalist 
    account</a> aan.
    </p>

    <p>
    Vertel vrienden en kennissen over de Aziatische hoornaar en 
    <a href="https://vespawatch.be/get-involved/">lees hier</a> hoe je verder kan deelnemen aan dit 
    project</a>. Feedback? Laat het ons weten door op deze email te antwoorden. 
    </p>

    <p>Met vriendelijke groeten,</p>

    <p>Het Vespa-Watch team</p>

    <small>
        <p>
        Dit is een éénmalige, automatische email die wordt verstuurd bij het melden van een 
        observatie op Vespa-Watch. We zullen je verder geen emails sturen. Bij een geverifieerde 
        melding van een <strong>nest</strong> van Aziatische hoornaars, kan je worden gecontacteerd 
        door bestrijders. Zie ons 
        <a href="https://vespawatch.be/about/privacy-policy/">privacybeleid</a>.
        </p>
    
        <p>
        Elke melding op Vespa-Watch is publiek beschikbaar als open data, maar voor bestrijding 
        worden enkel observaties in Vlaanderen gebruikt. Andere regio's en landen hebben vaak hun 
        <a href="https://vespawatch.be/about/links/">eigen invoerportalen</a> en 
        bestrijdingsprogramma's voor Aziatische hoornaar.
        </p>
    </small>
    
    <hr/>
    
    <p>Cher(e) {observer_name},</p>
    
    <p>
        Merci pour votre observation sur <a href="https://vespawatch.be">Vespa-Watch</a>. Grâce à vous, nous pouvons faire le point 
        sur l'invasion du frelon asiatique en Flandre.
    </p>
    
    <p>
        Votre observation est également disponible sur <a href="https://www.inaturalist.org/observations/{inat_id}">iNaturalist</a>, 
        où elle peut être vérifiée par 
        des bénévoles. Les observations comportant des photos inutilisables ou non prises par l'observateur 
        seront supprimées. Gardez un œil sur <a href="https://www.inaturalist.org/observations/{inat_id}">cette page</a> pour savoir quelles espèces vous avez vues. 
        Souhaitez-vous participer à l'identification et/ou transmettre des observations sous votre propre 
        nom ? Créez alors un <a href="https://www.inaturalist.org/signup">compte iNaturalist</a>.
    </p>
    
    <p>
        Parlez du frelon asiatique à vos amis et connaissances et <a href="https://vespawatch.be/get-involved/">lisez ici</a> comment vous pouvez participer à ce projet. Un retour d'information ? Faites-le nous savoir en répondant à ce courriel.
    </p>
    
    <p>
        <b>Habitez-vous en Wallonie?</b> Pour les observations en Wallonie, nous recommandons de reporter l'information directement via <a href="http://biodiversite.wallonie.be/fr/le-frelon-asiatique.html?IDC=5999">ce formulaire</a>.
    </p>
    
    <p>Bien à vous,</p>
    <p>L'équipe de Vespa-Watch</p>
    
    <small>
        <p>
        Il s'agit d'un courriel unique et automatique envoyé lors d'une observation sur Vespa-Watch. 
        Nous ne vous enverrons plus de courriels. Dans le cas d'un rapport vérifié d'un nid de 
        frelons asiatiques, vous pourriez être contacté par des services de gestion. 
        Voir notre <a href="https://vespawatch.be/about/privacy-policy/">politique de confidentialité</a>.
        </p>
        
        <p>
        Chaque rapport sur Vespa-Watch est disponible publiquement en tant que données ouvertes, 
        mais seules les observations en Flandre sont utilisées pour la gestion de l'espèce. D'autres 
        régions et pays ont souvent <a href="https://vespawatch.be/about/links/">leurs propres portails 
        d'encodage</a> et programmes de contrôle.
        </p>
    </small>
</body>
</html>
"""

# Other

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LANGUAGES_AVAILABLE_IN_SELECTOR = [
    ('nl', _('Dutch')),
    ('en', _('English')),
    ('fr', _('French')),
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

MARKDOWNX_IMAGE_MAX_SIZE = {
    'size': (1200, 600),
    'quality': 100
}

VESPAWATCH_EVIDENCE_OBS_FIELD_ID = 9770  # The identifier of the "vespawatch_evidence" observation field @iNaturalist
VESPAWATCH_ID_OBS_FIELD_ID = 9613 # The identifier of the "vespawatch_id" observation field @iNaturalist
VESPAWATCH_BEHAVIOUR_OBS_FIELD_ID = 10192
VESPAWATCH_PROJECT_ID = 22865  # vespawatch project ID @ iNaturalist
VESPAWATCH_PROJECT_URL = f"https://inaturalist.org/projects/{VESPAWATCH_PROJECT_ID}"
VESPAWATCH_USER_ID = 1263313  # vespawatch user ID @ iNaturalist

WEBSITE_NAME = "Vespa-Watch"

# Exported to templates

SETTINGS_EXPORT = [
    'DEBUG',
    'JS_DEBUG',
    'LANGUAGES',
    'LANGUAGES_AVAILABLE_IN_SELECTOR',
    'VESPAWATCH_EVIDENCE_OBS_FIELD_ID',
    'VESPAWATCH_ID_OBS_FIELD_ID',
    'VESPAWATCH_PROJECT_URL',
    'WEBSITE_NAME'
]
