# Generated by Django 2.2.13 on 2020-10-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0040_auto_20200915_1439'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='individual',
            unique_together={('taxon', 'observation_time', 'latitude', 'longitude', 'comments', 'inaturalist_id')},
        ),
        migrations.AlterUniqueTogether(
            name='nest',
            unique_together={('taxon', 'observation_time', 'latitude', 'longitude', 'comments', 'inaturalist_id')},
        ),
    ]
